[package]
name = "fozzie"
version = "0.1.0"
authors = ["Nick Pezza <npezza93@gmail.com>"]
edition = "2018"

[[bin]]
name = "fozzie"
path = "src/main.rs"

[dependencies]
"clap"="^2.31.2"
"termion"="^1.5.4"
"raw_tty"="^0.1.0"
"regex"="^1.3.4"

[dev-dependencies]
criterion = "^0.3"

[[bench]]
name = "matcher"
harness = false
