on: [push]

name: tests

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test
